/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:5214f2db-370c-456c-8c4a-c8a348ada679",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_LoM7etRWg",
    "aws_user_pools_web_client_id": "45bpb4e8malj80t52g95ogjph1",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "amplifytoolkit",
            "endpoint": "https://ghl9weghc7.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
