/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0eaf0878-279a-46ec-a1bf-27a6a95aa29b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_xklk7bBH3",
    "aws_user_pools_web_client_id": "19s1qflvttoo3uvvdt3llgm13u",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "amplifytoolkit",
            "endpoint": "https://1evprmj79d.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "BookTrip_dev",
            "alias": "$LATEST",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
